// Object Spy — injected page agent.
//
// This file is injected into the real, CDP-attached Chrome page via
// Page.addInitScript (so it survives navigations) and, for the page that was
// already loaded at attach time, via a one-off page.evaluate() as a safety
// net (see BrowserManager.start()). It never touches Node/VS Code APIs — it
// runs entirely inside the target page's JS context.
//
// Responsibilities:
//   1. Draw a single reused red overlay box over whatever element the mouse
//      is hovering, using getBoundingClientRect() + position:fixed (never
//      CSS outline, never per-hover DOM node churn).
//   2. Compute a short, relative locator (CSS or XPath, per config) for the
//      hovered element, and its live uniqueness count, entirely client-side.
//   3. On click (while Object Spy is enabled), finalize the locator for the
//      clicked element and report it to the extension host via
//      window.__objectSpyCapture (bound with page.exposeFunction).
//   4. While Generate Code recording is active, listen (without blocking
//      default behavior — a real click must still submit forms, navigate,
//      etc.) for click/change/keydown and report each as an action via
//      window.__objectSpyAction, so the host can turn it into code.
//
// Idempotent: safe to evaluate multiple times in the same document (guarded
// by window.__objectSpyInstalled) since the extension host re-applies it
// defensively on navigation.
//
// Edge cases handled deliberately:
//   - Shadow DOM: event targeting uses composedPath()[0], not e.target, so a
//     click inside an OPEN shadow root resolves to the real element rather
//     than the shadow host it retargets to at the document level. Live
//     uniqueness counting for CSS pierces open shadow roots too
//     (deepQuerySelectorAll — recurses into every open shadowRoot) so a bare
//     `[data-testid="x"]` inside a shadow root is correctly reported unique
//     instead of "0 matches" (native querySelectorAll never crosses shadow
//     boundaries on its own). This covers the attribute/id/name/placeholder
//     tiers fully; the ancestor-scoped CSS fallback tier deliberately never
//     crosses a shadow boundary when walking up for an anchor, since a
//     compound "ancestor descendant" selector spanning two different roots
//     can't be verified this way (each root is queried independently) — it
//     falls through to a less specific tier instead of risking a
//     never-true count. XPath's own document.evaluate() cannot pierce shadow
//     DOM at all — that mirrors Playwright's own XPath engine, so it's a
//     known, expected limitation rather than a bug: prefer CSS in
//     shadow-heavy apps. Closed shadow roots are inherently inaccessible to
//     any script (including Playwright itself) — nothing to do there.
//   - iframes: this same script is (re-)installed per-frame by
//     BrowserManager (Playwright's addInitScript/exposeFunction already
//     operate per-frame; see installPageAgent()) — same-origin AND
//     cross-origin, since CDP grants frame access the DOM's same-origin
//     policy would otherwise block. Each frame's instance is independent;
//     nothing here reaches across a frame boundary.
//   - Dynamic/generated ids: isStableId() filters out common
//     framework-autogenerated id shapes (React 18 useId, MUI, Radix, Chakra,
//     Ember, Angular Material/CDK) in addition to GUIDs and long hashes.
//   - Locator uniqueness is the top priority: computeLocatorInfo() never
//     settles for an ambiguous candidate while a better option is available.
//     It tries the primary tiered candidate, then a sibling-axis refinement
//     (XPath following-sibling::/preceding-sibling::, or CSS's forward-only
//     `~` combinator, anchored on a nearby sibling with its own stable
//     attribute/id), and only as an absolute last resort falls back to a
//     positional XPath predicate — `(relativeXPath)[n]` — which is
//     guaranteed unique by construction and still relative, never an
//     absolute /html/body/... path.
//   - Every captured element also reports elementName (a short camelCase
//     name derived from its visible text/stable attribute/tag), inIframe,
//     and inShadowDom, for the results table.
(function () {
  if (window.__objectSpyInstalled) {
    return;
  }
  window.__objectSpyInstalled = true;

  /** @type {{ locatorType: 'css' | 'xpath' }} */
  window.__objectSpyConfig = window.__objectSpyConfig || { locatorType: 'css' };
  window.__objectSpyEnabled = false;
  window.__objectSpyRecording = false;
  // True only while an ambiguous locator is awaiting resolution in the
  // panel. Deliberately does NOT block clicks (see onClick below) — the
  // whole point of this separate flag is that pausing must feel identical
  // to active recording from the page's perspective, never falling back to
  // Object Spy's own click-blocking capture mode just because a capture is
  // paused.
  window.__objectSpyRecordingPaused = false;

  window.__objectSpySetConfig = function (cfg) {
    window.__objectSpyConfig = Object.assign({}, window.__objectSpyConfig, cfg || {});
  };

  window.__objectSpySetEnabled = function (enabled) {
    window.__objectSpyEnabled = !!enabled;
    if (!window.__objectSpyEnabled) {
      hideOverlay();
    }
  };

  window.__objectSpySetRecording = function (enabled) {
    window.__objectSpyRecording = !!enabled;
    if (!enabled) {
      window.__objectSpyRecordingPaused = false;
    }
  };

  window.__objectSpySetRecordingPaused = function (paused) {
    window.__objectSpyRecordingPaused = !!paused;
  };

  // Computed once per frame/document — window.top is always safely
  // reference-comparable even cross-origin (only *reading properties* off
  // it would throw), so this correctly detects "running inside an iframe"
  // in every frame this script is installed into (see BrowserManager).
  var IN_IFRAME = (function () {
    try {
      return window.self !== window.top;
    } catch (e) {
      return true;
    }
  })();

  function isInShadowDom(el) {
    var root = typeof el.getRootNode === 'function' ? el.getRootNode() : null;
    return !!(root && root.host); // only ShadowRoot instances have a `.host`
  }

  /** Short, camelCase, human-readable name for an element: visible text,
   * else a stable attribute hint, else its tag — e.g. "loginButton",
   * "username", "div3". Used as the Elements table's "Element Name" column. */
  function elementNameFor(el) {
    var source = visibleText(el) || attrHint(el) || (el.tagName ? el.tagName.toLowerCase() : 'element');
    var words = source
      .replace(/[^a-zA-Z0-9]+/g, ' ')
      .trim()
      .split(/\s+/)
      .filter(Boolean)
      .slice(0, 4);
    if (!words.length) {
      return 'element';
    }
    var name = words[0].toLowerCase();
    for (var i = 1; i < words.length; i++) {
      name += words[i].charAt(0).toUpperCase() + words[i].slice(1).toLowerCase();
    }
    // This exact string is later reused verbatim as a Java/Python variable
    // name in Generate Code's Locators class (see codeGenerator.ts) — a
    // valid code identifier can never start with a digit (e.g. visible text
    // "123 Main St" would otherwise produce "123Main"), so guard against
    // that here rather than silently diverging between what the table shows
    // and what ends up usable in the generated code.
    if (/^[0-9]/.test(name)) {
      name = 'el' + name.charAt(0).toUpperCase() + name.slice(1);
    }
    return name;
  }

  function attrHint(el) {
    var attrs = STABLE_TEST_ATTRS_HINT;
    for (var i = 0; i < attrs.length; i++) {
      var v = el.getAttribute(attrs[i]);
      if (v) {
        return v;
      }
    }
    return '';
  }
  // Declared with `var` (hoisted) so attrHint above can reference it even
  // though STABLE_TEST_ATTRS itself is defined further down with the rest
  // of the locator engine — avoids duplicating the attribute list.
  var STABLE_TEST_ATTRS_HINT = ['data-testid', 'data-test', 'data-qa', 'data-cy', 'data-automation-id', 'name', 'placeholder', 'aria-label', 'id'];

  // ---------------------------------------------------------------------
  // Overlay: one reused element, positioned with position:fixed so viewport
  // coordinates from getBoundingClientRect() need no scroll-offset math.
  // ---------------------------------------------------------------------
  var overlay = null;
  function ensureOverlay() {
    if (overlay && overlay.isConnected) {
      return overlay;
    }
    overlay = document.createElement('div');
    overlay.id = '__object-spy-overlay';
    Object.assign(overlay.style, {
      position: 'fixed',
      left: '0px',
      top: '0px',
      width: '0px',
      height: '0px',
      border: '2px solid #ff3b30',
      background: 'rgba(255, 59, 48, 0.08)',
      boxSizing: 'border-box',
      pointerEvents: 'none',
      zIndex: '2147483647',
      transition: 'none',
      display: 'none'
    });
    (document.documentElement || document.body).appendChild(overlay);
    return overlay;
  }

  function showOverlayOn(el) {
    var box = ensureOverlay();
    var rect = el.getBoundingClientRect();
    box.style.left = rect.left + 'px';
    box.style.top = rect.top + 'px';
    box.style.width = rect.width + 'px';
    box.style.height = rect.height + 'px';
    box.style.display = 'block';
  }

  function hideOverlay() {
    if (overlay) {
      overlay.style.display = 'none';
    }
  }

  // ---------------------------------------------------------------------
  // Hover tracking: rAF-throttled position updates (cheap), debounced
  // "settle" for locator computation (more expensive: builds candidates and
  // counts live DOM matches).
  // ---------------------------------------------------------------------
  var rafPending = false;
  var lastEl = null;
  var settleTimer = null;
  var lastComputed = null; // cached { locatorType, locator, tier, qualityLabel, matches } for lastComputedEl
  var lastComputedEl = null; // the element lastComputed was actually computed for — NOT always lastEl:
  // lastEl updates immediately on mousemove, but lastComputed only after the
  // debounce below, so a click landing on a *new* element inside that debounce
  // window must not be attributed the *previous* element's cached locator.

  function isActive() {
    return window.__objectSpyEnabled || window.__objectSpyRecording;
  }

  // Prefer composedPath()[0] over e.target: inside an OPEN shadow root,
  // e.target is retargeted to the shadow host when observed from outside
  // the root (which our document-level listeners always are), but
  // composedPath() still exposes the true innermost element.
  function composedTarget(e) {
    var path = typeof e.composedPath === 'function' ? e.composedPath() : null;
    return path && path.length ? path[0] : e.target;
  }

  function onMouseMove(e) {
    if (!isActive()) {
      return;
    }
    var target = composedTarget(e);
    if (!target || target === overlay) {
      return;
    }
    lastEl = target;

    if (!rafPending) {
      rafPending = true;
      requestAnimationFrame(function () {
        rafPending = false;
        if (lastEl && isActive()) {
          showOverlayOn(lastEl);
        }
      });
    }

    clearTimeout(settleTimer);
    settleTimer = setTimeout(function () {
      if (lastEl && isActive()) {
        lastComputed = computeLocatorInfo(lastEl);
        lastComputedEl = lastEl;
      }
    }, 100);
  }

  function describeTarget(target, info) {
    return {
      tag: target.tagName ? target.tagName.toLowerCase() : '',
      text: visibleText(target),
      elementName: elementNameFor(target),
      locatorType: info.locatorType,
      locator: info.locator,
      tier: info.tier,
      qualityLabel: info.qualityLabel,
      matches: info.matches,
      inIframe: IN_IFRAME,
      inShadowDom: isInShadowDom(target)
    };
  }

  // Heuristic for "this click probably navigates/submits" — used by the
  // code generator to add a settle wait after the step (see codeGenerator.ts).
  function isSubmitLike(target) {
    var tag = target.tagName;
    if (tag === 'A') {
      return true;
    }
    if (tag === 'BUTTON') {
      var type = (target.getAttribute('type') || 'submit').toLowerCase();
      return type === 'submit';
    }
    if (tag === 'INPUT') {
      var itype = (target.type || '').toLowerCase();
      return itype === 'submit' || itype === 'button';
    }
    return false;
  }

  function onClick(e) {
    var target = composedTarget(e);
    if (!target || target === overlay) {
      return;
    }
    var info = target === lastComputedEl && lastComputed ? lastComputed : computeLocatorInfo(target);

    if (window.__objectSpyRecording) {
      // Recording mode: never block the click, whether actively capturing
      // or paused for an ambiguous-locator resolution — the real app must
      // actually navigate/submit/etc. so the recorded flow (and the app
      // itself) behaves exactly like it would with no extension attached at
      // all. Only suppress reporting a NEW action while paused; still let
      // the default action proceed either way.
      if (!window.__objectSpyRecordingPaused && typeof window.__objectSpyAction === 'function') {
        window.__objectSpyAction(
          Object.assign({ actionType: 'click', submitLike: isSubmitLike(target) }, describeTarget(target, info))
        );
      }
      return;
    }

    if (!window.__objectSpyEnabled) {
      return;
    }
    // Pure Object Spy mode: takes over the click entirely — capture, don't
    // navigate/submit.
    e.preventDefault();
    e.stopPropagation();
    e.stopImmediatePropagation();

    if (typeof window.__objectSpyCapture === 'function') {
      window.__objectSpyCapture(describeTarget(target, info));
    }
  }

  function reportAction(actionType, target, value) {
    if (!window.__objectSpyRecording || window.__objectSpyRecordingPaused || !target) {
      return;
    }
    var info = computeLocatorInfo(target);
    var payload = Object.assign({ actionType: actionType, value: value }, describeTarget(target, info));
    if (typeof window.__objectSpyAction === 'function') {
      window.__objectSpyAction(payload);
    }
  }

  function onChange(e) {
    if (!window.__objectSpyRecording) {
      return;
    }
    var target = composedTarget(e);
    if (!target) {
      return;
    }
    if (target.tagName === 'SELECT') {
      reportAction('selectOption', target, target.value);
    } else if (target.type === 'checkbox' || target.type === 'radio') {
      reportAction(target.checked ? 'check' : 'uncheck', target, undefined);
    } else {
      reportAction('fill', target, target.value);
    }
  }

  function onKeydown(e) {
    if (!window.__objectSpyRecording) {
      return;
    }
    // Only the key actions Playwright's press() is meaningfully used for —
    // continuous typing is already captured via the 'change' handler above.
    if (['Enter', 'Tab', 'Escape'].indexOf(e.key) === -1) {
      return;
    }
    reportAction('press', composedTarget(e), e.key);
  }

  document.addEventListener('mousemove', onMouseMove, true);
  document.addEventListener('click', onClick, true);
  document.addEventListener('change', onChange, true);
  document.addEventListener('keydown', onKeydown, true);

  // ---------------------------------------------------------------------
  // Locator engine
  // ---------------------------------------------------------------------

  var GUID_OR_HASH_RE = /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$|^[0-9a-f]{16,}$|^\d{5,}$/i;
  // Common framework-autogenerated id shapes: React 18 useId() (":r0:", also
  // wrapped by a component prefix like "field-:r1a:"), MUI, Radix, Chakra,
  // Headless UI, Reach UI, Angular Material/CDK, Ember, ExtJS.
  var FRAMEWORK_GENERATED_ID_RE =
    /^(mui|radix|chakra|headlessui|reach|mat|cdk|ember|ext-gen|react-select)[-:]|(^|-):r[0-9a-z]+:$/i;
  var STABLE_TEST_ATTRS = ['data-testid', 'data-test', 'data-qa', 'data-cy', 'data-automation-id'];

  function isStableId(id) {
    return !!id && !GUID_OR_HASH_RE.test(id) && !FRAMEWORK_GENERATED_ID_RE.test(id);
  }

  function isStableClass(cls) {
    // Filter out obviously generated/hashed utility classes (CSS-in-JS, css
    // modules, Tailwind's arbitrary/hash-like variants) — keep short,
    // hand-authored-looking class names only.
    return (
      !!cls &&
      cls.length <= 40 &&
      !/^(css|sc|jsx|emotion|makeStyles|MuiBox|_)[-_][a-z0-9]{4,}$/i.test(cls) &&
      !/[0-9a-f]{6,}/i.test(cls)
    );
  }

  // For bare identifiers used unquoted in a selector (IDs, class names).
  function cssEscape(value) {
    if (window.CSS && typeof window.CSS.escape === 'function') {
      return window.CSS.escape(value);
    }
    return String(value).replace(/([^\w-])/g, '\\$1');
  }

  // For values placed inside a quoted attribute selector, e.g. [aria-label="..."]
  // — only the quote character and backslash itself need escaping; escaping
  // spaces/punctuation here (as cssEscape does) is unnecessary noise.
  function cssStringEscape(value) {
    return String(value).replace(/\\/g, '\\\\').replace(/"/g, '\\"');
  }

  function xpathLiteral(value) {
    if (value.indexOf("'") === -1) {
      return "'" + value + "'";
    }
    if (value.indexOf('"') === -1) {
      return '"' + value + '"';
    }
    // Value contains both quote types — build a concat().
    var parts = value.split("'");
    return "concat('" + parts.join("', \"'\", '") + "')";
  }

  function visibleText(el) {
    var text = (el.innerText || el.textContent || '').trim().replace(/\s+/g, ' ');
    return text.length > 120 ? text.slice(0, 117) + '…' : text;
  }

  function directText(el) {
    // Text belonging directly to this element (not nested children) — used
    // for normalize-space() XPath matches so we don't match a huge ancestor.
    var text = '';
    for (var i = 0; i < el.childNodes.length; i++) {
      var node = el.childNodes[i];
      if (node.nodeType === Node.TEXT_NODE) {
        text += node.textContent;
      }
    }
    return text.trim().replace(/\s+/g, ' ');
  }

  /**
   * Like querySelectorAll, but also recurses into every open shadow root —
   * native querySelectorAll never crosses a shadow boundary on its own, so
   * without this, any locator on an element inside an open shadow root
   * would be (wrongly) reported as matching zero elements.
   */
  function deepQuerySelectorAll(selector) {
    var results = [];
    function collect(root) {
      var matches;
      try {
        matches = root.querySelectorAll(selector);
      } catch (e) {
        matches = [];
      }
      for (var i = 0; i < matches.length; i++) {
        results.push(matches[i]);
      }
      var all;
      try {
        all = root.querySelectorAll('*');
      } catch (e) {
        all = [];
      }
      for (var j = 0; j < all.length; j++) {
        if (all[j].shadowRoot) {
          collect(all[j].shadowRoot);
        }
      }
    }
    collect(document);
    return results;
  }

  function countCss(selector) {
    try {
      return deepQuerySelectorAll(selector).length;
    } catch (e) {
      return -1;
    }
  }

  /** All nodes an XPath expression matches, as a plain array — used both for
   * counting and (in the positional-index fallback) for finding exactly
   * where our target element sits among them. */
  function evaluateXPathNodes(xpath) {
    try {
      var result = document.evaluate(xpath, document, null, XPathResult.ORDERED_NODE_SNAPSHOT_TYPE, null);
      var nodes = [];
      for (var i = 0; i < result.snapshotLength; i++) {
        nodes.push(result.snapshotItem(i));
      }
      return nodes;
    } catch (e) {
      return [];
    }
  }

  function countXPath(xpath) {
    return evaluateXPathNodes(xpath).length;
  }

  function qualityLabelFor(tier, matches) {
    var tierLabel =
      tier === 'testid'
        ? 'Excellent'
        : tier === 'id'
        ? 'Excellent'
        : tier === 'aria'
        ? 'Good'
        : tier === 'css'
        ? 'Fair'
        : tier === 'sibling'
        ? 'Fair'
        : tier === 'index'
        ? 'Weak'
        : 'Weak';
    var uniqueLabel = matches === 1 ? 'Unique' : matches > 1 ? 'Ambiguous (' + matches + ')' : 'Not found';
    return tierLabel + ' · ' + uniqueLabel;
  }

  /**
   * Builds the best candidate CSS selector for an element, short and
   * relative — never a full path from html/body down. Returns
   * { css, tier } or null if nothing better than a generic fallback exists
   * (in which case the caller falls back to XPath).
   */
  function buildCssCandidate(el) {
    for (var i = 0; i < STABLE_TEST_ATTRS.length; i++) {
      var attr = STABLE_TEST_ATTRS[i];
      var val = el.getAttribute(attr);
      if (val) {
        return { css: '[' + attr + '="' + cssStringEscape(val) + '"]', tier: 'testid' };
      }
    }

    if (isStableId(el.id)) {
      return { css: '#' + cssEscape(el.id), tier: 'id' };
    }

    var ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) {
      return { css: el.tagName.toLowerCase() + '[aria-label="' + cssStringEscape(ariaLabel) + '"]', tier: 'aria' };
    }

    var role = el.getAttribute('role');
    if (role) {
      return { css: '[role="' + cssStringEscape(role) + '"]', tier: 'aria' };
    }

    var name = el.getAttribute('name');
    if (name && (el.tagName === 'INPUT' || el.tagName === 'SELECT' || el.tagName === 'TEXTAREA')) {
      return { css: el.tagName.toLowerCase() + '[name="' + cssStringEscape(name) + '"]', tier: 'css' };
    }

    var placeholder = el.getAttribute('placeholder');
    if (placeholder) {
      return { css: el.tagName.toLowerCase() + '[placeholder="' + cssStringEscape(placeholder) + '"]', tier: 'css' };
    }

    // Short relative selector scoped to the nearest stable ancestor: tag +
    // first stable class + :nth-of-type as a last disambiguator, walking at
    // most 2 levels up rather than the full ancestor chain to html/body.
    var stableClass = null;
    if (el.classList) {
      for (var c = 0; c < el.classList.length; c++) {
        if (isStableClass(el.classList[c])) {
          stableClass = el.classList[c];
          break;
        }
      }
    }
    var tag = el.tagName.toLowerCase();
    var base = stableClass ? tag + '.' + cssEscape(stableClass) : tag;

    var ancestor = findStableAncestor(el, 2);
    if (ancestor) {
      return { css: ancestor + ' ' + base, tier: 'css' };
    }

    return { css: base, tier: 'css' };
  }

  /** Looks up to `maxLevels` ancestors for a stable, short anchor selector. */
  function findStableAncestor(el, maxLevels) {
    var node = el.parentElement;
    var levels = 0;
    while (node && levels < maxLevels) {
      for (var i = 0; i < STABLE_TEST_ATTRS.length; i++) {
        var val = node.getAttribute(STABLE_TEST_ATTRS[i]);
        if (val) {
          return '[' + STABLE_TEST_ATTRS[i] + '="' + cssStringEscape(val) + '"]';
        }
      }
      if (isStableId(node.id)) {
        return '#' + cssEscape(node.id);
      }
      node = node.parentElement;
      levels++;
    }
    return null;
  }

  /**
   * Builds a short relative XPath — anchored on a stable ancestor when one
   * exists nearby, otherwise a direct attribute/text match. Never absolute
   * (never `/html/body/div[...]`).
   */
  function buildXPathCandidate(el) {
    var tag = el.tagName.toLowerCase();

    for (var i = 0; i < STABLE_TEST_ATTRS.length; i++) {
      var val = el.getAttribute(STABLE_TEST_ATTRS[i]);
      if (val) {
        return '//' + tag + '[@' + STABLE_TEST_ATTRS[i] + '=' + xpathLiteral(val) + ']';
      }
    }
    if (isStableId(el.id)) {
      return "//*[@id=" + xpathLiteral(el.id) + ']';
    }
    var ariaLabel = el.getAttribute('aria-label');
    if (ariaLabel) {
      return '//' + tag + '[@aria-label=' + xpathLiteral(ariaLabel) + ']';
    }
    var name = el.getAttribute('name');
    if (name) {
      return '//' + tag + '[@name=' + xpathLiteral(name) + ']';
    }
    var text = directText(el);
    if (text) {
      return '//' + tag + '[normalize-space()=' + xpathLiteral(text) + ']';
    }
    var placeholder = el.getAttribute('placeholder');
    if (placeholder) {
      return '//' + tag + '[@placeholder=' + xpathLiteral(placeholder) + ']';
    }

    // Last resort: anchor on the nearest stable ancestor and descend by tag
    // only — still relative, never an absolute index path from the root.
    var anchorNode = el.parentElement;
    var levels = 0;
    while (anchorNode && levels < 3) {
      if (isStableId(anchorNode.id)) {
        return "//*[@id=" + xpathLiteral(anchorNode.id) + ']//' + tag;
      }
      for (var j = 0; j < STABLE_TEST_ATTRS.length; j++) {
        var aval = anchorNode.getAttribute(STABLE_TEST_ATTRS[j]);
        if (aval) {
          return '//*[@' + STABLE_TEST_ATTRS[j] + '=' + xpathLiteral(aval) + ']//' + tag;
        }
      }
      anchorNode = anchorNode.parentElement;
      levels++;
    }
    return '//' + tag;
  }

  function computeXPathPrimary(el) {
    var xpath = buildXPathCandidate(el);
    var count = countXPath(xpath);
    var tier = xpath.indexOf('@data-') >= 0 || xpath.indexOf('@id') >= 0 ? 'testid' : 'xpath';
    return { locatorType: 'xpath', locator: xpath, tier: tier, matches: count };
  }

  function computeCssPrimary(el) {
    var candidate = buildCssCandidate(el);
    var count = countCss(candidate.css);
    return { locatorType: 'css', locator: candidate.css, tier: candidate.tier, matches: count };
  }

  /** A same-parent sibling with a stable attribute/id, within a few hops,
   * used to anchor a following-sibling/preceding-sibling (or CSS ~) locator
   * when the direct candidate alone isn't unique. */
  function stableAttrSelectorFor(node) {
    for (var i = 0; i < STABLE_TEST_ATTRS.length; i++) {
      var val = node.getAttribute(STABLE_TEST_ATTRS[i]);
      if (val) {
        return { css: '[' + STABLE_TEST_ATTRS[i] + '="' + cssStringEscape(val) + '"]', xpath: '@' + STABLE_TEST_ATTRS[i] + '=' + xpathLiteral(val) };
      }
    }
    if (isStableId(node.id)) {
      return { css: '#' + cssEscape(node.id), xpath: '@id=' + xpathLiteral(node.id) };
    }
    return null;
  }

  function findStableSiblingAnchor(el) {
    var prev = el.previousElementSibling;
    var distance = 1;
    while (prev && distance <= 5) {
      var prevAnchor = stableAttrSelectorFor(prev);
      if (prevAnchor) {
        return { anchor: prevAnchor, direction: 'following', distance: distance };
      }
      prev = prev.previousElementSibling;
      distance++;
    }
    var next = el.nextElementSibling;
    distance = 1;
    while (next && distance <= 5) {
      var nextAnchor = stableAttrSelectorFor(next);
      if (nextAnchor) {
        return { anchor: nextAnchor, direction: 'preceding', distance: distance };
      }
      next = next.nextElementSibling;
      distance++;
    }
    return null;
  }

  /**
   * Refines an ambiguous candidate using XPath's following-sibling::/
   * preceding-sibling:: axes (see the BrowserStack/scientecheasy XPath-axes
   * references this tiering follows), anchored on a nearby sibling that
   * itself has a stable attribute or id. Returns null when no such anchor
   * exists nearby, or (for CSS) when the only viable anchor is a *later*
   * sibling — CSS combinators only ever look forward in document order
   * (`+`/`~`), so there is no CSS equivalent of preceding-sibling::.
   */
  function trySiblingRefinement(el, locatorType) {
    var found = findStableSiblingAnchor(el);
    if (!found) {
      return null;
    }
    var tag = el.tagName.toLowerCase();

    if (locatorType === 'xpath') {
      var axis = found.direction === 'following' ? 'following-sibling' : 'preceding-sibling';
      var xpath = '//*[' + found.anchor.xpath + ']/' + axis + '::' + tag + '[' + found.distance + ']';
      return { locatorType: 'xpath', locator: xpath, tier: 'sibling', matches: countXPath(xpath) };
    }

    if (found.direction !== 'following') {
      return null; // no backward CSS combinator -- caller falls through to the index fallback
    }
    // '+' (adjacent) is exact at distance 1 -- no intermediate siblings to
    // account for. Beyond that, '~' (general) is inherently approximate:
    // it matches EVERY later sibling of that tag, not just the one exactly
    // `distance` hops away, so it's only useful when that happens to already
    // be unique; the live count() check below is what actually decides.
    var combinator = found.distance === 1 ? '+' : '~';
    var css = found.anchor.css + ' ' + combinator + ' ' + tag;
    return { locatorType: 'css', locator: css, tier: 'sibling', matches: countCss(css) };
  }

  /**
   * Absolute last resort — guarantees matches === 1 by construction (locator
   * uniqueness is the #1 priority: see the Master Build Prompt's locator
   * quality mandate). Expressed as a positional XPath predicate regardless
   * of the configured locator type: only XPath's document.evaluate() lets
   * this be verified natively against the live DOM, and Playwright's own
   * locator() auto-detects XPath from the leading "//"/"(" — so it still
   * works correctly in generated code even when Settings is set to CSS.
   * Still relative — never an absolute /html/body/... path.
   */
  function buildIndexFallback(el) {
    var baseXPath = buildXPathCandidate(el);
    var matches = evaluateXPathNodes(baseXPath);
    var index = matches.indexOf(el);
    if (index !== -1) {
      return { locatorType: 'xpath', locator: '(' + baseXPath + ')[' + (index + 1) + ']', tier: 'index', matches: 1 };
    }
    // Defensive: base candidate somehow didn't include el at all (shouldn't
    // normally happen) -- fall back to indexing purely by tag, document-wide.
    var tag = el.tagName.toLowerCase();
    var all = evaluateXPathNodes('//' + tag);
    var tagIndex = all.indexOf(el);
    if (tagIndex === -1) {
      return { locatorType: 'xpath', locator: baseXPath, tier: 'index', matches: matches.length };
    }
    return { locatorType: 'xpath', locator: '(//' + tag + ')[' + (tagIndex + 1) + ']', tier: 'index', matches: 1 };
  }

  function finalizeInfo(result) {
    return {
      locatorType: result.locatorType,
      locator: result.locator,
      tier: result.tier,
      qualityLabel: qualityLabelFor(result.tier, result.matches),
      matches: result.matches
    };
  }

  /**
   * Computes the best locator for `el` per the current config, verifying
   * uniqueness against the live DOM at every step (ground truth, never a
   * heuristic guess) — and never stopping at an ambiguous result while a
   * better option remains: primary candidate -> sibling-axis refinement ->
   * guaranteed-unique positional index.
   */
  function computeLocatorInfo(el) {
    var locatorType = (window.__objectSpyConfig && window.__objectSpyConfig.locatorType) || 'xpath';
    var primary = locatorType === 'xpath' ? computeXPathPrimary(el) : computeCssPrimary(el);
    if (primary.matches === 1) {
      return finalizeInfo(primary);
    }

    var sibling = trySiblingRefinement(el, locatorType);
    if (sibling && sibling.matches === 1) {
      return finalizeInfo(sibling);
    }

    return finalizeInfo(buildIndexFallback(el));
  }

  // ---------------------------------------------------------------------
  // "Highlight On Page" — find a previously-captured locator on the CURRENT
  // page and flash a rapidly-blinking red box around it for 5 seconds, so a
  // user picking a row in the Elements table can see exactly which element
  // it refers to. Separate from the hover overlay above: this one blinks,
  // is independent of Object Spy/recording being on, and self-removes.
  // ---------------------------------------------------------------------
  var flashOverlay = null;
  var flashTimer = null;
  var flashStyleInjected = false;

  function ensureFlashStyle() {
    if (flashStyleInjected) {
      return;
    }
    var style = document.createElement('style');
    style.textContent =
      '@keyframes __objectSpyBlink { 0%, 49% { opacity: 1; } 50%, 100% { opacity: 0; } }';
    document.head.appendChild(style);
    flashStyleInjected = true;
  }

  function findSingleElement(locatorType, locator) {
    if (locatorType === 'xpath') {
      return evaluateXPathNodes(locator)[0] || null;
    }
    return deepQuerySelectorAll(locator)[0] || null;
  }

  window.__objectSpyFlashHighlight = function (locatorType, locator) {
    var el = findSingleElement(locatorType, locator);
    if (!el) {
      return false;
    }

    ensureFlashStyle();
    clearTimeout(flashTimer);
    if (flashOverlay) {
      flashOverlay.remove();
    }

    if (typeof el.scrollIntoView === 'function') {
      el.scrollIntoView({ block: 'center', inline: 'center' });
    }

    flashOverlay = document.createElement('div');
    flashOverlay.id = '__object-spy-flash-overlay';
    Object.assign(flashOverlay.style, {
      position: 'fixed',
      border: '3px solid #ff3b30',
      background: 'rgba(255, 59, 48, 0.15)',
      boxSizing: 'border-box',
      pointerEvents: 'none',
      zIndex: '2147483647',
      animation: '__objectSpyBlink 0.3s steps(1, end) infinite'
    });
    (document.documentElement || document.body).appendChild(flashOverlay);

    // Position after the scroll above has had a chance to settle.
    setTimeout(function () {
      if (!flashOverlay) {
        return;
      }
      var rect = el.getBoundingClientRect();
      flashOverlay.style.left = rect.left + 'px';
      flashOverlay.style.top = rect.top + 'px';
      flashOverlay.style.width = rect.width + 'px';
      flashOverlay.style.height = rect.height + 'px';
    }, 150);

    flashTimer = setTimeout(function () {
      if (flashOverlay) {
        flashOverlay.remove();
        flashOverlay = null;
      }
    }, 5000);

    return true;
  };
})();
